# Generated by Django 4.1.1 on 2022-10-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='szkolenie_wst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=30)),
                ('name_business', models.CharField(max_length=100)),
                ('number_business', models.CharField(max_length=10)),
                ('number_phone', models.CharField(max_length=10)),
                ('number_of_people', models.IntegerField()),
                ('manager_ot_not', models.CharField(choices=[('1', 'Tak'), ('2', 'Nie')], max_length=2)),
                ('danger_or_not', models.CharField(choices=[('1', 'Tak'), ('2', 'Nie')], max_length=2)),
            ],
        ),
    ]
