# Generated by Django 4.1.1 on 2022-10-30 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_szkolenie_wst'),
    ]

    operations = [
        migrations.AddField(
            model_name='szkolenie_wst',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='szkolenie_wst',
            name='danger_or_not',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=3),
        ),
        migrations.AlterField(
            model_name='szkolenie_wst',
            name='manager_ot_not',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=3),
        ),
    ]
