# Generated by Django 4.1.1 on 2022-11-05 17:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_szkolenie_wst_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='szkolenie_wstepne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('nazwa_firmy', models.CharField(max_length=100)),
                ('numer_nip', models.CharField(max_length=10)),
                ('numer_telefonu', models.CharField(max_length=10)),
                ('liczba_osob', models.IntegerField()),
                ('kierownicze_czy_nie', models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=3)),
                ('niebezpiecznie_czy_nie', models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=3)),
                ('data', models.DateField(default=datetime.date.today)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='szkolenie_wst',
        ),
    ]
