# Generated by Django 4.1.1 on 2022-11-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_szkolenie_wstepne_delete_szkolenie_wst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='szkolenie_wstepne',
            name='data',
        ),
    ]
