# Generated by Django 4.1.1 on 2022-11-07 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_szkolenie_wstepne_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='szkolenie_wstepne',
            name='email',
            field=models.EmailField(default='@', max_length=254),
        ),
        migrations.AlterField(
            model_name='szkolenie_wstepne',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
