# Generated by Django 4.1.1 on 2022-11-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_szkolenie_wstepne_email_alter_szkolenie_wstepne_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szkolenie_wstepne',
            name='data',
            field=models.DateField(),
        ),
    ]
