# Generated by Django 4.1.1 on 2022-11-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_szkolenie_wstepne_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szkolenie_wstepne',
            name='numer_telefonu',
            field=models.CharField(max_length=11),
        ),
    ]
