# Generated by Django 4.1.1 on 2022-11-07 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_szkolenie_wstepne_numer_telefonu'),
    ]

    operations = [
        migrations.CreateModel(
            name='szkolenie_okresowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_szkolenia', models.CharField(choices=[('Pracodawcy i stanowiska kierownicze', 'Pracodawcy i stanowiska kierownicze'), ('Stanowiska robotnicze', 'Stanowiska robotnicze'), ('Stanowiska administracyjno-biurowe', 'Stanowiska administracyjno-biurowe'), ('Stanowiska inżynieryjno-techniczne', 'Stanowiska inżynieryjno-techniczne'), ('Stanowiska osób pełniących służbę BHP', 'Stanowiska osób pełniących służbę BHP')], max_length=50)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('nazwa_firmy', models.CharField(max_length=100)),
                ('numer_nip', models.CharField(max_length=10)),
                ('numer_telefonu', models.CharField(max_length=11)),
                ('liczba_osob', models.IntegerField()),
                ('niebezpiecznie_czy_nie', models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=3)),
                ('data', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
