# Generated by Django 4.1.1 on 2022-11-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_ocena_ryzyka'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocena_ryzyka',
            name='kod_zawodu',
            field=models.CharField(default='123456', max_length=6),
        ),
    ]
