# Generated by Django 4.1.1 on 2022-11-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_ocena_ryzyka_kod_zawodu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocena_ryzyka',
            name='kod_zawodu',
            field=models.CharField(max_length=6),
        ),
    ]
