# Generated by Django 4.1.1 on 2022-11-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_ocena_ryzyka_kod_zawodu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audyt',
            options={'verbose_name_plural': 'Audyty'},
        ),
        migrations.AlterModelOptions(
            name='ocena_ryzyka',
            options={'verbose_name_plural': 'Oceny ryzyka'},
        ),
        migrations.AlterModelOptions(
            name='szkolenie_inst_opp',
            options={'verbose_name_plural': 'Instrukcja Ochrony Przeciwpożarowej'},
        ),
        migrations.AlterModelOptions(
            name='szkolenie_okresowe',
            options={'verbose_name_plural': 'Szkolenia okresowe'},
        ),
        migrations.AlterModelOptions(
            name='szkolenie_opp',
            options={'verbose_name_plural': 'Szkolenia Ochrony Przeciwpożarowej'},
        ),
        migrations.AlterModelOptions(
            name='szkolenie_pp',
            options={'verbose_name_plural': 'Szkolenia Pierwsza Pomoc'},
        ),
        migrations.AlterModelOptions(
            name='szkolenie_wstepne',
            options={'verbose_name_plural': 'Szkolenia wstępne'},
        ),
    ]
