# Generated by Django 4.1.1 on 2022-11-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_audyt_options_alter_ocena_ryzyka_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Użytkownicy'},
        ),
    ]
